"""Generate catalog_gen.go from the client's item_prototype_hoc.tbl.

Usage: python gen_catalog.py <tables.bin or item_prototype_hoc.tbl> > catalog_gen.go

tables.bin is the Gameloft zip with 'GBMP' local headers; item_prototype_hoc.tbl
is an FTABLE. Column map (libAndroid 3.6.5a, Item_Prototype_LOL):
  col0 id, col1 lobby(1)/match(0), col2 type, col9 flags (bit 0x200000 = unique
  pattern, "unlimited use"), col10..18 pack counts, col24..32 pack item ids
  (Item_Prototype_LOL::GetPackItem @0x10bf1cc), col10 = proto+0x28 (spell /
  in-match wire id used by SyncPlayerInfoFromUserInfo for tablets and
  inscriptions), col33 name.
"""
import struct, sys, zipfile, zlib


def read_tbl(path):
    if path.endswith('.tbl'):
        return open(path, 'rb').read()
    d = open(path, 'rb').read()
    z = zipfile.ZipFile(path)
    zi = z.getinfo('tables/item_prototype_hoc.tbl')
    o = zi.header_offset
    nlen, elen = struct.unpack_from('<HH', d, o + 26)
    start = o + 30 + nlen + elen
    raw = d[start:start + zi.compress_size]
    return zlib.decompress(raw, -15) if zi.compress_type == 8 else raw


def parse_ftable(d):
    assert d[:6] == b'FTABLE'
    ver, nrows, ncols, _, typeoff, dataoff, rowsz, pooloff = struct.unpack_from('<8I', d, 8)
    types = d[typeoff:typeoff + ncols].decode()
    nints = rowsz // 4

    def s(v):
        return d[v:d.find(b'\0', v)].decode('utf-8', 'replace')

    rows = []
    for r in range(nrows):
        vals = struct.unpack_from('<%dI' % nints, d, dataoff + r * rowsz)
        rows.append([s(v) if types[i] == 's' else v for i, v in enumerate(vals[:ncols])])
    return rows


def main():
    rows = parse_ftable(read_tbl(sys.argv[1]))
    out = ["// Code generated by gen_catalog.py from item_prototype_hoc.tbl; DO NOT EDIT.", "",
           "package items", "", "var catalog = map[int]Item{"]
    for r in rows:
        if r[1] != 1:
            continue
        iid, typ, flags, name = r[0], r[2], r[9], r[33].replace('"', '\\"')
        pack = []
        for i in range(9):
            cid = r[24 + i]
            if cid:
                cnt = r[10 + i]
                if cnt > 0x5F5E100 or cnt <= 0:
                    cnt = 1
                pack.append((cid, cnt))
        unique = "true" if (flags >> 16) & 0x20 else "false"
        packs = ", ".join("{%d, %d}" % p for p in pack)
        wire = r[10] if typ in (13, 14) else 0
        out.append('\t%d: {ID: %d, Type: %d, Name: "%s", Unique: %s, Wire: %d, Pack: []PackEntry{%s}},'
                   % (iid, iid, typ, name, unique, wire, packs))
    out.append("}")
    print("\n".join(out))


if __name__ == '__main__':
    main()
